services:
  db-postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgres
    restart: always
    ports:
     - "5432:5432"
    env_file: 
     - ./config/postgres.env  
    networks:
     - backend 
    

volumes:
 postgres_data: {}
networks:
 backend:
  driver: bridge